os: osx
osx_image: xcode11.2
language: swift
script: xcodebuild clean build test -workspace TDD_MVP.xcworkspace -scheme "TDD_MVP_CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.2.2,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CORE_SIGNING_REQUIRED=NO